# Generated by Django 3.2.4 on 2021-06-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('paragraph', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='contactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('titleBlue', models.CharField(max_length=120)),
                ('paragraph', models.TextField(max_length=500)),
                ('email', models.EmailField(max_length=120)),
                ('mobileNo', models.IntegerField()),
                ('address', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=120)),
                ('percent', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='home_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_title', models.CharField(max_length=120)),
                ('title_blue', models.CharField(max_length=120)),
                ('paragraph', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='skill/%Y/%m/%d')),
                ('detail', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=120)),
                ('image', models.ImageField(blank=True, null=True, upload_to='skill/%Y/%m/%d')),
                ('paragraph', models.TextField(max_length=500)),
            ],
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-updated', '-timestamp']},
        ),
    ]
