# Generated by Django 3.2.4 on 2021-06-29 08:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210629_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='skillPink',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
    ]
