# Generated by Django 3.2.4 on 2021-06-29 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_service_skillpink'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='home_detail',
            new_name='homeDetail',
        ),
    ]
