# Generated by Django 3.2.4 on 2021-06-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_rename_home_detail_homedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='skill/%Y/%m/%d'),
        ),
    ]
